---
- name: CVE-2023-20198 Playbook
  gather_facts: false
  hosts: all
  vars:
    uri:
      - "webui/logoutconfirm.html?menu=1"
      - "webui/logoutconfirm.html?logon_hash=1"
    ports:
      - 80
      - 443
    pattern: '^([a-f0-9]{18})\s*$'
  tasks:
    - name: Connect to device
      ansible.builtin.uri:
        url: "http{{ (item.1 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}/{{ item.0 }}"
        method: POST
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
      loop: "{{ uri | product(ports) }}"
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine device response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} found listening on uri / port {{ item.item }} with suspicious response: {{ item.content }}"
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 200
        - item.content | trim | list | length == 18
        - item.content | regex_search(pattern, multiline=True)
