---
- name: CVE-2023-20198 Playbook
  gather_facts: false
  hosts: all
  vars:
    uri: "webui/logoutconfirm.html?logon_hash=1"
    pattern: '(0[xX])?[A-Fa-f0-9]+$'
  tasks:
    - name: Connect to device
      ansible.builtin.uri:
        url: "http{{ (item | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}/{{ uri }}"
        method: POST
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
      loop:
        - 80
        - 443
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine device response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} found listening on port {{ item.item }} with suspicious response: {{ item.content }}"
      loop: "{{ response.results }}"
      when: 
        - response is defined
        - item.content | lengeth < 32 
        - item.content | map('trim') | list | length == 18
        #- item.content | regex_search(pattern, multiline=True, ignorecase=False)
